print('\033[31mDesafio 049\033[m')
print('-=' * 20)
print('\033[35mTabuada simplificada\033[m')
print('-=' * 20)
n = int(input('Digite um número para ver a sua tabuada: '))
"""print('-' * 10)
print('{} x 1 = {}'.format(n, n * 1))
print('{} x 2 = {}'.format(n, n * 2))
print('{} x 3 = {}'.format(n, n * 3))
print('{} x 4 = {}'.format(n, n * 4))
print('{} x 5 = {}'.format(n, n * 5))
print('{} x 6 = {}'.format(n, n * 6))
print('{} x 7 = {}'.format(n, n * 7))
print('{} x 8 = {}'.format(n, n * 8))
print('{} x 9 = {}'.format(n, n * 9))
print('{} x 10 = {}'.format(n, n * 10))
print('-' * 10)"""
print('-' * 12)
for c in range(1, 11):
    print('{} x {} = {}'.format(n, c, n * c))
print('-' * 12)
